# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('role', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('confirm_code', models.CharField(blank=True, max_length=6)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
