# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
